### ISSUE TITLE
Add opening hours

### ISSUE THREAD

**Issue by marfavi** [AnalogIO/coffeecard_app#214] opened 2022-03-17 11:08 UTC
No design yet, but let's display our normal opening hours somewhere.

Requires some design and some discussion

![image](https://user-images.githubusercontent.com/21163286/158796346-99b12de7-0db3-4104-91b5-bfd81af85bb7.png)

**Comment by fremartini** [comment] 2022-03-17 13:10
duplicate of #163?

**Closed** 2022-03-17 14:24 UTC
Labels: blocked, P0, P1, needs-design, discuss
