### ISSUE TITLE
MobilePay Purchase flow fails - State is null

### ISSUE THREAD

**Issue by duckth** [AnalogIO/coffeecard_app#350] opened 2022-10-11 17:25 UTC
MobilePay purchase flow fails when trying to create MobilePayPaymentDetails object after geting response from PurchaseRepository
PurchaseRepository.initiatePurchase returns a response with `state = null` and causes an exception:
`CastError (type 'Null' is not a subtype of type 'String' in type cast)`

**Comment by TTA777** [comment] 2022-10-11 18:08
Just to add to this, in my older version of the generated code, state is correctly marked as nullable. Whether this change is caused by a change in the library that generate the httpClient code, or the OpenApiSpec I'm not sure of yet

**Comment by jonasanker** [comment] 2022-10-12 08:27
Bug is introduced in the package upgrade of `swagger_dart_code_generator` to `2.7.8` in Pull Request https://github.com/AnalogIO/coffeecard_app/pull/348

Analog Core does not support nullability officially yet. This requires an update of the codebase. See issue https://github.com/AnalogIO/analog-core/issues/82

Probably is it the best to rollback the package to the old version for now

**Closed** 2022-10-18 14:20 UTC
Labels: bug
